import { FaRegCircle } from "react-icons/fa";
import { FaPerson } from "react-icons/fa6";
import { FaIdCard } from "react-icons/fa";
import { FaGear } from "react-icons/fa6";

export const sidebarContents = [
  {
    id: 1,
    title: "Person Management",
    icon: <FaPerson />,
    children: [
      {
        id: 1,
        title: "Person Information",
        icon: <FaRegCircle />,
        href: "/admin/person/person",
      },
      {
        id: 2,
        title: "Leave Registration",
        icon: <FaRegCircle />,
        href: "/admin/person/person",
      },
    ],
  },
  {
    id: 2,
    title: "Attendance Management",
    icon: <FaIdCard />,
    children: [
      {
        id: 1,
        title: "Punch Record",
        icon: <FaRegCircle />,
        href: "/admin/attendance/punch-record",
      },
      {
        id: 2,
        title: "Leave Registration",
        icon: <FaRegCircle />,
        href: "/admin/attendance/punch-record",
      },
    ],
  },
  {
    id: 3,
    title: "System Settings",
    icon: <FaGear />,
    children: [
      {
        id: 1,
        title: "Device Management",
        icon: <FaRegCircle />,
        href: "/admin/system/device",
      },
      {
        id: 2,
        title: "Company Information",
        icon: <FaRegCircle />,
        href: "/admin/system/customerInfo",
      },
      {
        id: 3,
        title: "User Account",
        icon: <FaRegCircle />,
        href: "/admin/system/users",
      },
    ],
  },
];

export const users = [
  {
    id: 1,
    code: "AY2024",
    department: "Instructors",
    gender: "Female",
    cardNo: "123455",
    mobileNo: "09012312312",
    registerDate: "2024-09-23",
    name: "Deborah Uzo",
    email: "debbyuzo@gmail.com",
    desc: "A normal user",
    operate: "",
  },
  {
    id: 2,
    code: "1",
    department: "Staff",
    gender: "Male",
    cardNo: "123455",
    mobileNo: "09012312312",
    registerDate: "2024-11-23",
    name: "Samuel Obiechie",
    email: "samobi@gmail.com",
    desc: "An Admin user",
    operate: "",
  },
  {
    id: 3,
    code: "2",
    department: "Teacher",
    gender: "Male",
    cardNo: "123223321",
    mobileNo: "09012312312",
    registerDate: "2024-09-11",
    name: "Habib Habib",
    email: "habibhabib@gmail.com",
    desc: "A super admin user",
    operate: "",
  },
  {
    id: 4,
    code: "2",
    department: "Teacher",
    gender: "Male",
    cardNo: "123223321",
    mobileNo: "09012312312",
    registerDate: "2024-09-11",
    name: "Habib Habib",
    email: "habibhabib@gmail.com",
    desc: "A super admin user",
    operate: "",
  },
  {
    id: 5,
    code: "2",
    department: "Teacher",
    gender: "Male",
    cardNo: "123223321",
    mobileNo: "09012312312",
    registerDate: "2024-09-11",
    name: "Habib Habib",
    email: "habibhabib@gmail.com",
    desc: "A super admin user",
    operate: "",
  },
  {
    id: 6,
    code: "2",
    department: "Teacher",
    gender: "Male",
    cardNo: "123223321",
    mobileNo: "09012312312",
    registerDate: "2024-09-11",
    name: "Habib Habib",
    email: "habibhabib@gmail.com",
    desc: "A super admin user",
    operate: "",
  },
  {
    id: 7,
    code: "2",
    department: "Teacher",
    gender: "Male",
    cardNo: "123223321",
    mobileNo: "09012312312",
    registerDate: "2024-09-11",
    name: "Habib Habib",
    email: "habibhabib@gmail.com",
    desc: "A super admin user",
    operate: "",
  },
];
